export default {
  banner: require("./Images/banner.png"),
  noImages: require("./Images/no_images.png"),
  loading: require("./ic_animation.json"),
  backgroundSuccess: require("./Images/back_Ground_Success.png"),
  iconVN: require("./Images/ic_vietnam.png"),
  iconEN: require("./Images/ic_eng.png"),
  iconAVT: require("./Images/Avatar.png"),
  logoDefault: require("./icons/logo_default.png"),
  brickTest: require("./Images/img_BrickTest.png"),
  brgTransaction: require("./Images/img_bgr_transactionDetail.png"),
  iconWareBook: require("./Images/ic_WareBook.png"),
  iconHome: require("./Images/ic_Home.png"),
  iconImportBook: require("./Images/ic_importBook.png"),
  iconOutBook: require("./Images/ic_outputBook.png"),
  iconInBook: require("./Images/in_In.png"),
  // success: require("../assets/success.png"),
  // warning: require("../assets/warning.png"),
  // danger: require("../assets/danger.png"),
  // info: require("../assets/info.png"),
  // imagesSource: require("./local-assets/backspace.png"),
};
