import { StyleSheet } from "react-native";
import {
  colors,
  fontSize,
  margin,
  padding,
  scaleHeight,
  scaleWidth,
} from "../../../theme";

export const styles = StyleSheet.create({
  ROOT: {
    backgroundColor: "#F3f4f9",
    flex: 1,
  },
  btnLibrary: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.navyBlue,
    borderRadius: 8,
    paddingHorizontal: scaleWidth(10),
    paddingVertical: scaleHeight(7),
    marginBottom: scaleHeight(10),
  },
  viewViewDetail: {
    marginHorizontal: scaleWidth(16),
    marginVertical: scaleHeight(20),
  },
  textWeight400Blue: {
    fontSize: fontSize.size12,
    fontWeight: "400",
    color: colors.palette.navyBlue,
    marginLeft: scaleWidth(4),
  },
  btnCamera: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.navyBlue,
    borderRadius: 8,
    paddingHorizontal: scaleWidth(10),
    paddingVertical: scaleHeight(7),
  },
  textTitleViewPrice: {
    fontWeight: "500",
    fontSize: fontSize.size12,
    color: colors.palette.dolphin,
    lineHeight: scaleHeight(14),
  },
  btnAddProperties: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    paddingVertical: scaleHeight(7),
    borderRadius: 8,
    borderColor: colors.navyBlue,
  },
  viewDetails: {
    marginVertical: scaleHeight(margin.margin_10),
    borderWidth: scaleHeight(1),
    borderColor: colors.palette.ghostWhite,
    borderRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    shadowColor: "#3A43E5",
    shadowOpacity: 0.25,
    backgroundColor: colors.palette.neutral100,
  },
  viewTitleDetail: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: scaleHeight(margin.margin_12),
    marginBottom: scaleHeight(padding.padding_12),
    paddingHorizontal: scaleWidth(padding.padding_12),
  },
  viewLine2: {
    borderWidth: scaleHeight(0.5),
    borderColor: colors.palette.ghostWhite,
  },
  textTitleView: {
    fontSize: fontSize.size14,
    fontWeight: "700",
    marginBottom: scaleHeight(15),
  },
  textWeight400Black: {
    fontSize: fontSize.size13,
    fontWeight: "400",
    color: colors.palette.nero,
  },
  textWeight400Dolphin: {
    fontSize: fontSize.size13,
    fontWeight: "400",
    color: colors.palette.dolphin,
  },
  viewLineSwitchUnit: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: scaleHeight(15),
  },
  textWeight600: { fontSize: fontSize.size14, fontWeight: "600" },
  viewAttribute: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: scaleHeight(16),
    marginHorizontal: scaleWidth(margin.margin_16),
  },
  viewGroupBtn: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    backgroundColor: "white",
    paddingVertical: scaleHeight(20),
  },
  viewBtnCancel: {
    width: scaleWidth(165),
    height: scaleHeight(48),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: colors.palette.veryLightGrey,
  },
  viewBtnConfirm: {
    width: scaleWidth(150),
    height: scaleHeight(48),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: colors.palette.navyBlue,
  },
  viewBtnInMorInfo: {
    borderWidth: 1,
    alignItems: "center",
    paddingVertical: scaleHeight(6),
    paddingHorizontal: scaleWidth(8),
    borderColor: colors.palette.navyBlue,
    borderRadius: 4,
    marginLeft: scaleWidth(8),
  },
  textBtnMorInfo: {
    color: colors.palette.navyBlue,
    fontSize: fontSize.size10,
    fontWeight: "400",
    lineHeight: scaleHeight(12.1),
  },
});
